# This .yml file is used to specify the conda environment that should be loaded into the binder instance

name: CEGO
dependencies:
  - python=3.8
  - matplotlib
  - scipy
  - pip
  - pip:
    - "git+git://github.com/usnistgov/CEGO.git"