name: cibuildwheel

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4
      - name: checkout submodules
        run: git submodule update --init --recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      # # Used to host cibuildwheel
      # - uses: actions/setup-python@v2

      # - name: Install cibuildwheel
      #   run: python -m pip install cibuildwheel==2.22.0 build

      # - name: Make sdist
      #   run: python -m build . --sdist --outdir wheelhouse

      # - name: Build wheels
      #   run: python -m cibuildwheel --output-dir wheelhouse
      #   # to supply options, put them in 'env', like:
      #   env:
      #     CIBW_ARCHS: auto64
      #     CIBW_ARCHS_MACOS: universal2
      #     CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=10.15
      #     CIBW_BUILD_VERBOSITY_MACOS: 2
      #     # CIBW_SKIP: "*musllinux*"

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ strategy.job-index }}
          path: |
            ./wheelhouse/*.whl
            ./wheelhouse/*.tar.gz

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: dist-sdist
          path: dist/*.tar.gz


  merge_wheels:
   runs-on: ubuntu-latest
   needs: [build_wheels, build_sdist]
   steps:
     - name: Merge Artifacts
       uses: actions/upload-artifact/merge@v4
       with:
         name: dist
         pattern: dist-*