name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: mkdir
      run: mkdir -p CEGO/build && cd CEGO/build
    - name: cmake config
      run: cd CEGO/build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCEGO_ALL=ON
    - name: cmake make
      run: cmake --build CEGO/build --config Release
    - name: run Catch tests
      run: cd CEGO/build && ctest --verbose